customhost = "mydatabase.cpxqtrxb8b5q.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin12345"
customdb = "mydatabase"
custombucket = "my-project2bucket"
customregion = "us-east-1"
